"use client"
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { Calendar } from "@/components/ui/calendar"
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"

export function CalendarView() {
  const [month, setMonth] = useState(new Date()), [events, setEvents] = useState<any[]>([]), [selected, setSelected] = useState<Date | undefined>(), [open, setOpen] = useState(false)
  useEffect(() => { fetch(`/api/calendar/events?month=${month.getMonth() + 1}&year=${month.getFullYear()}`).then(r => r.json()).then(d => setEvents(d.data || [])) }, [month])
  const key = (d: Date) => d.toISOString().slice(0, 10), grouped = useMemo(() => events.reduce((all, event) => ({ ...all, [event.date.slice(0, 10)]: [...(all[event.date.slice(0, 10)] || []), event] }), {}), [events])
  const todayEvents = selected ? grouped[key(selected)] || [] : [], upcoming = events.filter(e => new Date(e.date) >= new Date()).sort((a,b) => +new Date(a.date) - +new Date(b.date)).slice(0, 7)
  return <div className="grid gap-6 lg:grid-cols-4"><div className="hidden rounded-[2rem] border border-border bg-card p-5 md:block lg:col-span-3"><Calendar mode="single" month={month} onMonthChange={setMonth} selected={selected} onSelect={day => { setSelected(day); setOpen(Boolean(day)) }} components={{ DayButton: ({ day, ...props }: any) => <button {...props} className="relative flex aspect-square w-full flex-col items-center justify-center rounded-lg hover:bg-muted">{day.date.getDate()}<span className="flex gap-0.5">{(grouped[key(day.date)] || []).slice(0, 3).map((e: any) => <i key={e.id} className="size-1.5 rounded-full" style={{ background: e.color }} />)}</span></button> }} /></div><aside className="rounded-[2rem] border border-border bg-card p-5"><h2 className="font-semibold">Upcoming this week</h2><div className="mt-4 space-y-3">{upcoming.map((event: any) => <Link key={event.id} href={event.link} className="block rounded-xl border-l-4 bg-muted/40 p-3 text-sm" style={{ borderColor: event.color }}><p className="font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{new Date(event.date).toLocaleDateString()}</p></Link>) || <p className="text-sm text-muted-foreground">No upcoming events.</p>}</div></aside><div className="lg:col-span-4"><div className="flex flex-wrap gap-4 text-sm">{[{t:"Premium due",c:"#2563eb"},{t:"Follow-up",c:"#9333ea"},{t:"Birthday",c:"#db2777"},{t:"Maturity",c:"#ea580c"},{t:"Claim",c:"#16a34a"}].map(i => <span key={i.t} className="flex items-center gap-2"><i className="size-2 rounded-full" style={{background:i.c}} />{i.t}</span>)}</div></div><Sheet open={open} onOpenChange={setOpen}><SheetContent><SheetHeader><SheetTitle>{selected?.toLocaleDateString()}</SheetTitle></SheetHeader><div className="space-y-3">{todayEvents.map((event: any) => <Link key={event.id} href={event.link} className="block rounded-xl border-l-4 p-3" style={{borderColor:event.color}}>{event.title}</Link>)}{!todayEvents.length && <p className="text-muted-foreground">No events on this day.</p>}</div></SheetContent></Sheet></div>
}
