import { NextResponse } from "next/server"
import { connectDB } from "@/lib/db"
import { getSession } from "@/lib/auth"
import { Policy } from "@/models/Policy"
import { PolicyHistory } from "@/models/PolicyHistory"
import { logAction } from "@/lib/audit"
import { User } from "@/models/User"
import { Branch } from "@/models/Branch"
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { await connectDB(); const session = await getSession(); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (["AGENT", "DEVELOPMENT_OFFICER"].includes(session.role)) return NextResponse.json({ success: false, error: "Only managers may reassign policies." }, { status: 403 }); const { id } = await params; const { agentId } = await request.json(); const policy = await Policy.findById(id); const agent = await User.findOne({ _id: agentId, role: "AGENT", isActive: true }); if (!policy || !agent) return NextResponse.json({ success: false, error: "Policy or active agent not found." }, { status: 404 }); const branch = await Branch.findOne({ code: agent.branch }); if (!branch) return NextResponse.json({ success: false, error: "Target agent has no branch." }, { status: 400 }); if ((session.role === "BRANCH_MANAGER" && branch.code !== session.branch) || (session.role === "REGIONAL_ADMIN" && branch.region !== session.region)) return NextResponse.json({ success: false, error: "Target agent is outside your scope." }, { status: 403 }); const oldAgent = policy.agent; const oldManager = policy.manager; const oldBranch = policy.branch; policy.agent = agent._id; policy.manager = agent.manager; policy.branch = branch._id; await policy.save(); await PolicyHistory.insertMany([{ policy: policy._id, field: "agent", oldValue: oldAgent, newValue: agent._id, changedBy: session.userId }, { policy: policy._id, field: "manager", oldValue: oldManager, newValue: agent.manager, changedBy: session.userId }, { policy: policy._id, field: "branch", oldValue: oldBranch, newValue: branch._id, changedBy: session.userId }]); await logAction(session, "REASSIGNED_POLICY", "Policy", id, { agent: oldAgent, manager: oldManager, branch: oldBranch }, { agent: agent._id, manager: agent.manager, branch: branch._id }, request); return NextResponse.json({ success: true, data: policy }) }
