import { NextResponse } from "next/server"
import { connectDB } from "@/lib/db"
import { getSession } from "@/lib/auth"
import { Policy, policyStatuses } from "@/models/Policy"
import { PolicyHistory } from "@/models/PolicyHistory"
import { User } from "@/models/User"
import { Branch } from "@/models/Branch"

const transitions: Record<string, string[]> = { PENDING: ["ACTIVE", "CANCELLED"], ACTIVE: ["LAPSED", "EXPIRED", "MATURED", "CANCELLED", "CLAIM_SETTLED"], LAPSED: ["ACTIVE", "CANCELLED"], EXPIRED: [], MATURED: ["CLAIM_SETTLED"], CANCELLED: [], CLAIM_SETTLED: [] }
async function allowed(id: string) { const session = await getSession(); if (!session) return { session, policy: null }; const policy = await Policy.findById(id); if (!policy) return { session, policy: null }; if (session.role === "SUPER_ADMIN" || (session.role === "AGENT" && policy.agent.toString() === session.userId) || (session.role === "DEVELOPMENT_OFFICER" && policy.manager?.toString() === session.userId)) return { session, policy }; const branch = await Branch.findById(policy.branch); const ok = (session.role === "BRANCH_MANAGER" && branch?.code === session.branch) || (session.role === "REGIONAL_ADMIN" && branch?.region === session.region); return { session, policy: ok ? policy : null } }
const maturity = (start: Date | string, term: number) => { const d = new Date(start); d.setFullYear(d.getFullYear() + Number(term)); return d }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectDB(); const { id } = await params; const { session, policy } = await allowed(id); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (!policy) return NextResponse.json({ success: false, error: "Policy not found or forbidden." }, { status: 404 }); const history = await PolicyHistory.find({ policy: policy._id }).populate("changedBy", "name").sort({ changedAt: -1 }).lean(); return NextResponse.json({ success: true, data: await policy.populate(["customer", "agent", "branch"]), history }) }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { await connectDB(); const { id } = await params; const { session, policy } = await allowed(id); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (!policy) return NextResponse.json({ success: false, error: "Policy not found or forbidden." }, { status: 404 }); const body = await request.json(); if (body.status && (!policyStatuses.includes(body.status) || !transitions[policy.status].includes(body.status))) return NextResponse.json({ success: false, error: `Cannot change ${policy.status} to ${body.status}.` }, { status: 400 }); const fields = ["planName", "policyTerm", "premiumAmount", "premiumMode", "sumAssured", "startDate", "lastPremiumPaidDate", "status"]; const histories = []; for (const field of fields) { if (body[field] !== undefined && String(policy.get(field) ?? "") !== String(body[field] ?? "")) histories.push({ policy: policy._id, field, oldValue: policy.get(field), newValue: body[field], changedBy: session.userId, changedAt: new Date() }) } if (!histories.length) return NextResponse.json({ success: true, data: policy }); for (const entry of histories) policy.set(entry.field, entry.newValue); if (body.policyTerm !== undefined || body.startDate !== undefined) { const old = policy.maturityDate; policy.maturityDate = maturity(body.startDate ?? policy.startDate, body.policyTerm ?? policy.policyTerm); histories.push({ policy: policy._id, field: "maturityDate", oldValue: old, newValue: policy.maturityDate, changedBy: session.userId, changedAt: new Date() }) } await policy.save(); await PolicyHistory.insertMany(histories); return NextResponse.json({ success: true, data: policy }) }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectDB(); const { id } = await params; const { session, policy } = await allowed(id); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (!policy) return NextResponse.json({ success: false, error: "Policy not found or forbidden." }, { status: 404 }); if (!transitions[policy.status].includes("CANCELLED")) return NextResponse.json({ success: false, error: "This policy can no longer be cancelled." }, { status: 400 }); const oldValue = policy.status; policy.status = "CANCELLED"; await policy.save(); await PolicyHistory.create({ policy: policy._id, field: "status", oldValue, newValue: "CANCELLED", changedBy: session.userId }); return NextResponse.json({ success: true, data: { id } }) }
