import { NextResponse } from "next/server"
import { connectDB } from "@/lib/db"
import { getSession } from "@/lib/auth"
import { Policy } from "@/models/Policy"
import { Customer } from "@/models/Customer"
import { User } from "@/models/User"
import { Branch } from "@/models/Branch"
import { generateScheduleForPolicy } from "@/lib/premiums"
import { logAction } from "@/lib/audit"

const maturity = (start: string | Date, term: number) => { const date = new Date(start); date.setFullYear(date.getFullYear() + Number(term)); return date }
async function scope(session: NonNullable<Awaited<ReturnType<typeof getSession>>>) { if (session.role === "SUPER_ADMIN") return {}; if (session.role === "AGENT") return { agent: session.userId }; if (session.role === "DEVELOPMENT_OFFICER") return { manager: session.userId }; if (session.role === "BRANCH_MANAGER") { const branch = await Branch.findOne({ code: session.branch }).select("_id"); return { branch: branch?._id } } const branches = await Branch.find({ region: session.region }).distinct("_id"); return { branch: { $in: branches } } }
async function nextNumber() { const year = new Date().getFullYear(); const latest = await Policy.findOne({ policyNumber: new RegExp(`^POL-${year}-`) }).sort({ policyNumber: -1 }).select("policyNumber").lean() as { policyNumber?: string } | null; return `POL-${year}-${String((Number(latest?.policyNumber?.split("-").at(-1)) || 0) + 1).padStart(6, "0")}` }
export async function GET(request: Request) { await connectDB(); const session = await getSession(); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); const p = new URL(request.url).searchParams; const filter: Record<string, unknown> = { ...await scope(session) }; if (p.get("status")) filter.status = p.get("status"); if (p.get("plan")) filter.planName = { $regex: p.get("plan"), $options: "i" }; if (p.get("agent")) filter.agent = p.get("agent"); if (p.get("from") || p.get("to")) filter.startDate = { ...(p.get("from") ? { $gte: new Date(p.get("from")!) } : {}), ...(p.get("to") ? { $lte: new Date(p.get("to")!) } : {}) }; if (p.get("search")) filter.policyNumber = { $regex: p.get("search"), $options: "i" }; const data = await Policy.find(filter).populate("customer", "name").populate("agent", "name").sort({ createdAt: -1 }).lean(); return NextResponse.json({ success: true, data }) }
export async function POST(request: Request) { await connectDB(); const session = await getSession(); if (!session) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); const body = await request.json(); const { customerId, planName, policyTerm, premiumAmount, premiumMode, sumAssured, startDate, agentId } = body; if (!customerId || !planName || !policyTerm || !premiumAmount || !premiumMode || !sumAssured || !startDate) return NextResponse.json({ success: false, error: "Customer, plan, term, premium, sum assured, and start date are required." }, { status: 400 }); const customer = await Customer.findById(customerId); if (!customer || !customer.isActive) return NextResponse.json({ success: false, error: "Choose an active customer." }, { status: 400 }); const agent = await User.findById(session.role === "AGENT" ? session.userId : agentId || customer.agent); const branch = agent ? await Branch.findOne({ code: agent.branch }) : null; if (!agent || agent.role !== "AGENT" || !branch) return NextResponse.json({ success: false, error: "A valid agent is required." }, { status: 400 }); const policy = await Policy.create({ policyNumber: await nextNumber(), customer: customer._id, agent: agent._id, manager: agent.manager, branch: branch._id, planName, policyTerm, premiumAmount, premiumMode, sumAssured, startDate, maturityDate: maturity(startDate, policyTerm), status: body.status || "PENDING" }); await generateScheduleForPolicy(policy); await logAction(session, "CREATED_POLICY", "Policy", policy._id.toString(), null, { policyNumber: policy.policyNumber, customer: customer._id, agent: agent._id, branch: branch._id, premiumAmount }, request); return NextResponse.json({ success: true, data: policy }) }
